### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by chris1879** [mubastan/mpeg7fex#2]
Hi!
There might be a memory leak in the following function:
The memory of pBin will not released;

kind regards
Christian

int ColorStructureExtractionTool::UnifyBins(unsigned long Norm, int nTargSize)
{
	double *pBin;
	int iTargBin, iOrigBin;
	int nOrigSize = m_Descriptor->GetSize();

	if (nTargSize == nOrigSize)
		return 0;

	// Only down quantize
	assert ( nTargSize < nOrigSize );

	// Grab temp space
	pBin = new double [nTargSize];
	assert(pBin);
	for (iTargBin = 0; iTargBin < nTargSize; iTargBin++)
		pBin[iTargBin] = 0.0;

	int iTargSpace = GetColorQuantSpace(nTargSize);
	int iOrigSpace = GetColorQuantSpace(nOrigSize);

	// Unify
	for (iOrigBin = 0; iOrigBin < nOrigSize; iOrigBin++)
	{
		iTargBin = TransformBinIndex(iOrigBin, iOrigSpace, iTargSpace);
		pBin[iTargBin] += m_Descriptor->GetElement(iOrigBin);
	}

	// Resize the descriptor
	m_Descriptor->SetSize(nTargSize);

	// Clip and insert
	for (iTargBin = 0; iTargBin < nTargSize; iTargBin++)
	{
		if (pBin[iTargBin] > Norm)
			pBin[iTargBin] = Norm;

		m_Descriptor->SetElement(iTargBin, pBin[iTargBin]);
	}

	return 0;
}

**Comment by mubastan** [comment]
Hi Christian,

Thank you very much for pointing out the memory leak. I have just fixed it by adding `delete[] pBin;` right before `return 0;`.

This part of the library was written by the MPEG-7 committee long time ago, and it is quite messy. I already fixed some bugs, but there might still be other bugs (did not check); so, contributions are welcome.
The best would be to check the whole library using some tool, like valgrind. Unfortunately, I do not have time for that.

Best regards.
