### ISSUE TITLE
further memory leaks and issues

### ISSUE THREAD

**Issue by chris1879** [mubastan/mpeg7fex#3]
Hi Muhammet,

I have found some further issues, a part of them further memory leaks.
Below is my git diff

best regards
Christian

diff --git a/Descriptors/DominantColor.cpp b/Descriptors/DominantColor.cpp
index ca65f4e..389d776 100644
--- a/Descriptors/DominantColor.cpp
+++ b/Descriptors/DominantColor.cpp
@@ -63,7 +63,14 @@ m_Quantizer(0)
 //----------------------------------------------------------------------------
 DominantColorDescriptor::~DominantColorDescriptor()
 {
-  // will be released by the clients!
+  // chris1879, 2018-02-17^M
+^M
+  if (m_dc)^M
+     delete m_dc;^M
+^M
+  delete m_ColorSpace;^M
+  delete m_Quantizer;^M
+^M
 }

diff --git a/Descriptors/ScalableColor.cpp b/Descriptors/ScalableColor.cpp
index afaf0eb..81999fc 100644
--- a/Descriptors/ScalableColor.cpp
+++ b/Descriptors/ScalableColor.cpp
@@ -12,16 +12,22 @@ using namespace XM;
 ScalableColorDescriptor::ScalableColorDescriptor():
 m_ScalableHistogram(0),
 m_NumberOfCoefficients(0),
-m_NumberOfBitplanesDiscarded(0)
+m_NumberOfBitplanesDiscarded(0),^M
+m_Sign(0) // chris1879, lack of initializing the pointer, possibility of crash if not null^M
 {
 }

 //----------------------------------------------------------------------------
 ScalableColorDescriptor::~ScalableColorDescriptor()
 {
+  if (m_ScalableHistogram)^M
+     delete [] m_ScalableHistogram;^M

-       if (m_ScalableHistogram) delete [] m_ScalableHistogram;
+  // fixed chris1879 17.02.2018^M
+  // memory leak, not freed^M

+  if (m_Sign) ^M
+     delete [] m_Sign; ^M
 }

 //----------------------------------------------------------------------------
diff --git a/Extraction/ColorStructureExtraction.cpp b/Extraction/ColorStructureExtraction.cpp
index 704cd07..2a732cf 100644
--- a/Extraction/ColorStructureExtraction.cpp
+++ b/Extraction/ColorStructureExtraction.cpp
@@ -851,9 +851,10 @@ int ColorStructureExtractionTool::UnifyBins(unsigned long Norm, int nTargSize)

                m_Descriptor->SetElement(iTargBin, pBin[iTargBin]);
        }
-
-       delete[] pBin;
-
+^M
+    // corr. chris1879, 2018-02-18^M
+    delete [] pBin;^M
+^M
        return 0;
 }

diff --git a/Extraction/imgutil.c b/Extraction/imgutil.c
index 5dd52e0..04751d4 100644
--- a/Extraction/imgutil.c
+++ b/Extraction/imgutil.c
@@ -316,6 +316,13 @@ int mergecb(float *B,float **cb,unsigned char *P,int npt,int N,float thresh,int
   if (N==1) return N;

   count=(int *)malloc(sizeof(int)*N);
+  ^M
+  // chris1879, count not initialized,^M
+  // in the next line the entries of it are summed up;^M
+  // this could cause wrong results^M
+^M
+  memset (count, 0, sizeof (int)*N); // ^M
+  ^M
   for (l=0;l<npt;l++) count[P[l]]++;

   dist=(float **)fmatrix(N,N);

**Comment by mubastan** [comment]
Hi Christian,

Again, thanks a lot.
I have just fixed the issues.

I noticed another issue: m_Sign was not initialized to 0 in the constructor (ScalableColorDescriptor).
I changed the malloc to calloc in imutil.c

As I said before, the code is very messy, hard to maintain; it might still have other issues, which may pop up on some platform, but work correctly on some other.

Best regards.
