### ISSUE TITLE
resetDescriptor does not work correctly

### ISSUE THREAD

**Issue by chris1879** [mubastan/mpeg7fex#4]
Hi,

 In the file dominantcolor.cpp the memory allocation for m_dc is not initialized

  m_dc = new DOMCOL[dc_number];

The function "resetDescriptor" does NOT work, because you set the dc_number AFTER
calling resetDescriptor, where you take the m_DominantColorsNumber and that is at the beginning zero.
So there is no initalizing.

BR,
Christian

/----------------------------------------------------------------------------
void DominantColorDescriptor::SetDominantColorsNumber(int dc_number)
{
  if (dc_number != m_DominantColorsNumber) {
    if (m_dc)
      delete [] m_dc;
    m_dc = new DOMCOL[dc_number];

    // fix it, not initialized
    memset (m_dc, 0, sizeof (DOMCOL)*dc_number);

	// set values to zero - by mb - may not be crucial here since they are assigned in SetDominantColors() below (no aggregation, etc)
	this->resetDescriptor();

	m_DominantColorsNumber = dc_number;
  }

**Comment by mubastan** [comment]
This is right; resetDescriptor may not work properly if dc_number has changed. This is problematic when the client wants to explicitly reset the descriptor; otherwise it is not an issue, since the contents of m_dc will be overwritten anyway (no need to initialize m_dc, unless it is accessed prior to extraction; but good to initialize).

**Comment by chris1879** [comment]
Hi Mubastan,

I have tested it on windows platform. Even the first time it does not initialize. Before, when there was no initilaizing I got unpredictible values as results than zero.

So, with initializing we are on the secure side. :-)

BR,
Christian

**Comment by mubastan** [comment]
Right. The updated version should be okey. The initialization should now work properly.
Thanks.
