### ISSUE TITLE
Testcase for GoF(P) Descriptor

### ISSUE THREAD

**Issue by chris1879** [mubastan/mpeg7fex#6]
Hi,
Do you have a testcase for the gof(p)  descriptor. I can't find any in the test file.

BR,
Christian

**Comment by mubastan** [comment]
Hi,
Test case for GoF was not included, since it requires a video or a sequence of frames.
However, it is very easy to use. Feature.h includes comments on how to use it:

```
GoF* gofd = new GoF( 1, video->getWidth(), video->getHeight());
while(...){
	// read/get frame

	// add the frame to the group
	gofd->addFrame1( frame );
}
// end
gofd->end();

// get the descriptor
XM::ScalableColorDescriptor* scdi = gofd->scdi;

//release gofd (descriptor is not released by the destructor, release it when you are done with it)
delete gofd;
```

**Comment by chris1879** [comment]
Hi,

Thank you for your code snippet. 

I will use it for a sequence of pictures (gop) not for videos.
Do you have also test data for it ? I will compare my results with yours, if they are correct ?

BR
Christian

**Comment by mubastan** [comment]
Unfortunately, I do not have a test case and result.
