### ISSUE TITLE
Error in compilation ‘m_sign’ was not declared in this scope

### ISSUE THREAD

**Issue by saxenarohit** [mubastan/mpeg7fex#8]
I got this error while compiling on Ubuntu using codeblocks

mpeg7fex-master/Descriptors/ScalableColor.cpp|24|error: ‘m_sign’ was not declared in this scope|

**Comment by mubastan** [comment]
Right, it should have been `m_Sign` (I do not know how it was changed to `m_sign`). It should be ok now.
